"""message

Revision ID: fe151e32a3af
Revises: 
Create Date: 2025-07-27 23:13:05.157264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe151e32a3af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_login_activity')
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('score_time_stamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('score_time_stamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.create_table('user_login_activity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('reminder_time', sa.TIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
